---
# Example yaml params file used for testing
# the params object and its dependencies
node:
  id: "pneumonoultramicroscopicsilicovolcanoconios="
  paths:
    cert: "~/.elixxir/cert.crt"
    key:  "~/.elixxir/key.pem"
    log:  "~/.elixxir/server.log"
  addresses:
    - "127.0.0.1:80"
    - "127.0.0.1:80"
    - "127.0.0.1:80"
database:
  name: "name"
  username: "username"
  password: "password"
  addresses:
    - "127.0.0.1:80"
    - "127.0.0.1:80"
    - "127.0.0.1:80"
gateways:
  paths:
    cert: "~/.elixxir/gateway.crt"
  addresses:
    - "127.0.0.1:80"
    - "127.0.0.1:80"
    - "127.0.0.1:80"
permissioning:
  paths:
    cert: "~/.elixxir/permissioning.crt"
  address: "127.0.0.1:80"
  regcode: "pneumonoultramicroscopicsilicovolcanoconios="
global:
  batch: 20
  skipreg: true
  groups:
    cmix:
      prime: "17"
      smallprime: "11"
      generator: "4"
    e2e:
      prime: "0x11"
      smallprime: "0x0B"
      generator: "0x04"
...
